import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    ignores: [
      // ALL AUTOGENERATED CODE - NEVER LINT THESE
      "**/src/generated/**",
      "**/src/generated/prisma/**",
      "**/src/generated/prisma/runtime/**",
      "**/src/generated/prisma/*.js",
      "**/src/generated/prisma/*.d.ts",
      "**/src/graphql/generated/**",
      "**/prisma/generated/**",
      "**/prisma/runtime/**",

      // WebAssembly and runtime files
      "**/wasm*.js",
      "**/wasm-engine*.js",
      "**/wasm-compiler*.js",
      "**/runtime/**",

      // Development and test files
      "**/src/app/wizard-demo/**",
      "**/src/lib/wizard/**",
      "**/src/ui/Wizard.tsx",
      "**/scripts/**",
      "**/tests/**",
      "**/*.stories.*",
      "**/*.test.*",

      // Build artifacts
      "**/.next/**",
      "**/out/**",
      "**/dist/**",
    ],
    rules: {
      // Strict TypeScript rules - temporarily relaxed for build
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-unused-vars": "warn",
      "@typescript-eslint/no-unused-expressions": "warn",
      "@typescript-eslint/no-this-alias": "warn",
      "@typescript-eslint/no-require-imports": "warn",
      "@typescript-eslint/no-empty-object-type": "warn",
      "@typescript-eslint/explicit-function-return-type": "off",
      "@typescript-eslint/explicit-module-boundary-types": "off",

      // Chakra UI v2 usage - allow all v2 imports and patterns
      // Note: Project is using Chakra UI v2 with glass frosty theme
      // "no-restricted-imports": [], // Disabled for v2 compatibility
      // "no-restricted-syntax": [], // Disabled for v2 compatibility
    },
  },
];

export default eslintConfig;
